os:
  - Visual Studio 2015

platform:
  - x64
  
configuration:
  - Release
  
branches:
  only:
    - master
    
build:
  verbosity: detailed
  
install:
  - git submodule update --init --recursive
  - set PATH=C:\Program Files\CMake\bin;%PATH%

environment:
  matrix:
    - env_arch: "x64"
      build_type: "Release"
    - env_arch: "x64"
      build_type: "Debug"
    - env_arch: "x86"
      build_type: "Release"
    - env_arch: "x86"
      build_type: "Debug"
   
before_build:
- cmd: |-
    mkdir build
    cd build
    mkdir %build_type%
    cmake .. -A %env_arch% 
  
build_script:
  - cmake --build . --config %build_type% --target install

test_script:
  - ctest -V

artifacts:
  - path: build
    name: build
 
on_failure:
- dir
- 7z a about_failed.zip scan_out
- ps: Push-AppveyorArtifact about_failed.zip
