os:
  - Visual Studio 2015

platform:
  - x86
  - x64
  
configuration:
  - Release
  
branches:
  only:
    - master

install:
  - git submodule update --init --recursive
  - set PATH=C:\Program Files\CMake\bin;%PATH%

build:
  verbosity: detailed
  
environment:
  matrix:
    - env_arch: "x64"
      build_type: "Release"
    - env_arch: "x64"
      build_type: "Debug"
    - env_arch: "x86"
      build_type: "Release"
    - env_arch: "x86"
      build_type: "Debug"
      
build_script:
  - mkdir build
  - cd build
  - if [%env_arch%]==[x64] (
    - if [%build_type%]==[Release] (
        cmake .. -A x64 -DCMAKE_BUILD_TYPE="Release" )
    - if [%build_type%]==[Debug] (
        cmake .. -A x64 -DCMAKE_BUILD_TYPE="Debug" )
        )
  - if [%env_arch%]==[x86] (
    - if [%build_type%]==[Release] (
        cmake .. -A x86 -DCMAKE_BUILD_TYPE="Release" )
    - if [%build_type%]==[Debug] (
        cmake .. -A x86 -DCMAKE_BUILD_TYPE="Debug" )
        )

test_script:
  - ctest -V
  
artifacts:
  - path: build
    name: build
 
on_failure:
- dir
- 7z a about_failed.zip scan_out
- ps: Push-AppveyorArtifact about_failed.zip
