os:
  - Visual Studio 2015

platform:
  - x64
  
configuration:
  - Release
  
branches:
  only:
    - master
    
build:
  verbosity: detailed
  
install:
  - git submodule update --init --recursive
  - set PATH=C:\Program Files\CMake\bin;%PATH%

environment:
  artifactName: $(APPVEYOR_PROJECT_NAME)-$(APPVEYOR_REPO_COMMIT)
  matrix:
    - env_arch: "x64"
    - env_arch: "x86"

before_build:
  - mkdir build
  - cd build
  - if [%env_arch%]==[x64] (
    cmake .. -A x64 )
  - if [%env_arch%]==[x86] (
    cmake .. )
  - cmake -DPESIEVE_AS_STATIC_LIB=ON ..
  
build_script:
  - cmake --build . --config %CONFIGURATION% --target install

after_build:
  - mkdir %artifactName%
  - cp *.exe %artifactName%
  - cp *.dll %artifactName%

test_script:
  - ctest -V

artifacts:
  - path: build\%artifactName%
 
on_failure:
- dir
- 7z a about_failed.zip scan_out
- ps: Push-AppveyorArtifact about_failed.zip
